application: gofastbreak
version: 1
runtime: go
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /images
  static_dir: images
  
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
  
- url: /.*
  script: _go_app